export interface CreateSpaceResponse {
  id: string;
  name: string;
  private: boolean;
  statuses?: (StatusesEntity)[] | null;
  multiple_assignees: boolean;
  features: Features;
  archived: boolean;
}
export interface StatusesEntity {
  id: string;
  status: string;
  type: string;
  orderindex: number;
  color: string;
}
export interface Features {
  due_dates: DueDates;
  sprints: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  points: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  custom_items: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  tags: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  time_estimates: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  checklists: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  zoom: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  milestones: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  custom_fields: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  remap_dependencies: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  dependency_warning: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  multiple_assignees: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  portfolios: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
  emails: SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails;
}
export interface DueDates {
  enabled: boolean;
  start_date: boolean;
  remap_due_dates: boolean;
  remap_closed_due_date: boolean;
}
export interface SprintsOrPointsOrCustomItemsOrTagsOrTimeEstimatesOrChecklistsOrZoomOrMilestonesOrCustomFieldsOrRemapDependenciesOrDependencyWarningOrMultipleAssigneesOrPortfoliosOrEmails {
  enabled: boolean;
}
